name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.OKEN }}
        issue-message: "Issue aah' first issue"
        pr-message: "Wait 15min of workflow runs , we will automatically merged your pull request "
